//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int idDoc { get; set; }
        public string docName { get; set; }
        public Nullable<int> docTypeID { get; set; }
        public string note { get; set; }
        public Nullable<decimal> confidenceScore { get; set; }
    
        public virtual duplicateDetail duplicateDetail { get; set; }
    }
}
