//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class duplicateDetail
    {
        public duplicateDetail()
        {
            this.documents = new HashSet<document>();
        }
    
        public int idDuplicateType { get; set; }
        public string duplicateDetails { get; set; }
    
        public virtual ICollection<document> documents { get; set; }
    }
}
